apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: wanderlust
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /data/wanderlust/db
    type: DirectoryOrCreate    
